### ISSUE TITLE
Create a docsite

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/italian-anki#13]
Create an mkdocs-based documentation site and set up CI to automatically publish to GitHub pages. Document the tools and general information about deck structure and contents. Add a contributing section.

**Comment by joshrotenberg** [comment]
Incorporate the following gist into a grammar reference: https://gist.github.com/joshrotenberg/935ec69e7bb296bb83bfe0d83239593a

**Comment by joshrotenberg** [comment]
# MkDocs Documentation Site Implementation Plan

## Overview
This plan outlines the steps to implement a basic documentation site for the Italian Anki project using MkDocs with Material theme. The site will be published to GitHub Pages via GitHub Actions.

## Task Checklist

### Initial Setup
- [ ] Install MkDocs and Material theme
  ```bash
  pip install mkdocs mkdocs-material
  ```
- [ ] Initialize MkDocs in the repository
  ```bash
  mkdocs new .
  ```
- [ ] Configure MkDocs with Material theme in `mkdocs.yml`
  ```yaml
  site_name: Italian Anki Decks
  site_description: A collection of Anki decks for learning Italian at different proficiency levels
  repo_url: https://github.com/joshrotenberg/italian-anki
  theme:
    name: material
    palette:
      primary: indigo
      accent: indigo
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.expand
      - navigation.indexes
      - content.code.copy
  ```

### Content Creation
- [ ] Create introduction page (`docs/index.md`)
  - [ ] Project overview
  - [ ] Target audience
  - [ ] Key features
- [ ] Create usage guide (`docs/usage/index.md`)
  - [ ] How to use prebuilt decks
  - [ ] How to import decks into Anki
  - [ ] How to study with the decks
- [ ] Create build guide (`docs/build/index.md`)
  - [ ] Requirements
  - [ ] Building decks from source
  - [ ] Different build modes
- [ ] Create contribution guide (`docs/contributing/index.md`)
  - [ ] How to contribute
  - [ ] Development workflow
  - [ ] Code style and guidelines
- [ ] Create forking guide (`docs/forking/index.md`)
  - [ ] How to fork the repository
  - [ ] How to customize for your own needs
  - [ ] How to set up your own GitHub Pages
- [ ] Create grammar reference (`docs/grammar/index.md`)
  - [ ] Incorporate content from the gist mentioned in the issue
  - [ ] Structure grammar content by level (A1, A2, etc.)
- [ ] Create learning resources page (`docs/resources/index.md`)
  - [ ] YouTube channels
  - [ ] Podcasts
  - [ ] Books and websites
  - [ ] Apps and other tools

### Navigation Structure
- [ ] Configure navigation in `mkdocs.yml`
  ```yaml
  nav:
    - Home: index.md
    - Usage Guide: usage/index.md
    - Building Decks: build/index.md
    - Contributing: contributing/index.md
    - Forking the Project: forking/index.md
    - Grammar Reference: grammar/index.md
    - Learning Resources: resources/index.md
  ```

### GitHub Actions Setup
- [ ] Create GitHub Actions workflow for MkDocs deployment
  - [ ] Create `.github/workflows/docs.yml` file
  ```yaml
  name: Deploy MkDocs
  on:
    push:
      branches:
        - main
    workflow_dispatch:
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install mkdocs mkdocs-material
        - name: Deploy docs
          run: mkdocs gh-deploy --force
  ```

### Testing and Refinement
- [ ] Test documentation site locally
  ```bash
  mkdocs serve
  ```
- [ ] Review and refine content
- [ ] Check mobile responsiveness
- [ ] Ensure all links work correctly
- [ ] Add screenshots and examples where appropriate

### Final Steps
- [ ] Push changes to GitHub
- [ ] Verify GitHub Actions workflow runs successfully
- [ ] Confirm documentation site is published to GitHub Pages
- [ ] Update README.md with link to documentation site

## Implementation Notes
- The documentation should be clear and concise, targeting both beginners and experienced users
- Use consistent formatting and style throughout the documentation
- Include code examples and screenshots where helpful
- Ensure the grammar reference is well-structured and easy to navigate
- Make the learning resources section comprehensive but curated

Once this plan is implemented, the Italian Anki project will have a professional documentation site that helps users understand, use, and contribute to the project.
