### ISSUE TITLE
Migrate Project to TOML and Support Markdown Formatting

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/italian-anki#6]
**Title:**  
Migrate deck sources to TOML format and support Markdown formatting inside fields

**Description:**  
Migrate all existing Anki deck source files from JSON to TOML format.  
Allow Markdown syntax (e.g., `**bold**`, `*italic*`, lists) inside fields for richer card formatting.

**Checklist:**
- [ ] Convert all `.json` files inside `a1/` and `a2/` to `.toml` format.
- [ ] Allow Markdown inside `fields` arrays.
- [ ] Update `generate.py` to read `.toml` files.
- [ ] Leave `.json` files untouched until manual verification.
- [ ] Update project README to document TOML and Markdown usage.

**Sample TOML Note Structures:**

**Basic Note:**
```toml
deck = "a1::verbs"
model = "basic"
[[notes]]
note_id = 10001
fields = ["**mangiare**", "to eat"]
tags = ["a1", "verbs"]
```

**Cloze Note:**
```toml
deck = "a1::expressions"
model = "cloze"
[[notes]]
note_id = 10002
fields = ["Sono andato al {{c1::cinema}} ieri sera."]
tags = ["a1", "expressions"]
```

**Deliverables:**
- All decks migrated to TOML.
- No functional regressions.
- Updated project documentation.

---
